# Configuration for librarian-puppet. For example:
# 
forge "http://forge.puppetlabs.com"
# 
# mod "puppetlabs/razor"
# mod "puppetlabs/ntp", "0.0.3"
# 
# mod "apt",
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
# 
mod "stdlib",
   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

#mod "puppi",
   #:git => "git://github.com/example42/puppi.git"

#mod "solr",
   #:git => "git://github.com/example42/puppet-solr.git"

mod "nanliu/staging"
